name: Build and Push Image
on:
  push:
    branches:
      - 'main'
env:
  IMAGE_REPOSITORY_MAIN: brezyweather
  IMAGE_TAG: 1.0.0

jobs:
  build:
    name: Build BrezyWeather container image
    runs-on: ubuntu-latest

    steps:
    - name: Setup docker build X
      uses: docker/setup-buildx-action@v3.0.0

    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Docker push
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        tags: ${{ secrets.ACR_SERVER }}/${{ env.IMAGE_REPOSITORY_NAME }}:${{ env.IMAGE_TAG }}
